const {requireDatabase, slug} = require('../util');

/**
 * @param {string} slug a slug
 * @return {Promise} Promise that resolves number of input slug in
 * slug_counter table and rejects error generated by query function
 */
const getSlugCounter = function(slug) {
  return new Promise((resolve, reject) => {
    const connection = requireDatabase();
    connection.connect();

    connection.query(
        'SELECT * FROM slug_counter WHERE ?',
        [{slug}],
        function(err, res) {
          if (!err) {
            if (res.length > 0) {
              resolve(res[0].counter);
            } else resolve(0);
          } else reject(err);
        });

    connection.end();
  });
};

/**
 * @param {string} url page url
 * @param {string} title usually page title (anime, anime + episodeNum, ...)
 * @return {Promise} Promise that resolves slug of newly added url
 *  and rejects error generated by query function
 */
const addUrl = function(url, title) {
  return new Promise(async (resolve, reject) => {
    const generatedSlug = slug(title);
    const slugCounter = await getSlugCounter(generatedSlug);

    addSlug(generatedSlug, slugCounter + 1)
        .then((addedSlug) => {
          const connection = requireDatabase();
          connection.connect();

          let slug = addedSlug;

          if (slugCounter != 0) {
            slug = slug.concat(`-${slugCounter + 1}`);
          }

          connection.query(
              'INSERT INTO slugs SET ?',
              {slug, url},
              (err) => {
                if (err) throw err;
                else resolve(slug);
              });

          connection.end();
        })
        .catch((error) => {
          reject(error);
        });
  });
};

/**
 * @param {string} slug is slug to be added
 * @param {number} counter if slugCounter = 0 then create new entry with
 * counter = 1 else increment the counter of the existing slug by one
 * @return {Promise} Promise that resolves added Slug and rejects error
 * generated by query function
 */
const addSlug = function(slug, counter) {
  return new Promise((resolve, reject) => {
    const connection = requireDatabase();
    connection.connect();

    let queryString;
    let params;

    if (counter == 1) {
      queryString = 'INSERT INTO slug_counter SET ?';
      params = {counter, slug};
    } else {
      queryString = 'UPDATE slug_counter SET ? WHERE ?';
      params = [{counter}, {slug}];
    }

    connection.query(queryString, params, (err) => {
      if (err) reject(err);
      else resolve(slug);
    });

    connection.end();
  });
};

/**
 * @param {string} url is page url be added
 * @param {string} title usually page title (anime, anime + episodeNum, ...)
 * @return {Promise} Promise that resolves slug if it exist already in database
 * and adds new Slug if it doesn't exist
 */
exports.getSlug = function(url, title) {
  return new Promise((resolve, reject) => {
    const connection = requireDatabase();
    connection.connect();

    connection.query('SELECT * FROM slugs WHERE ?', {url}, (err, res) => {
      if (err) {
        reject(err);
      } else {
        if (res.length > 0) resolve(res[0].slug);
        else addUrl(url, title).then(resolve).catch(reject);
      }
    });

    connection.end();
  });
};

exports.addUrl = addUrl;
exports.getSlugCounter = getSlugCounter;
